name: Issue Automation

on:
  issues:
    types: [opened]

jobs:
  process_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout gh
      uses: actions/checkout@v2

    - name: Setup GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Assign to project board and add labels
      run: |
        issueNumber=${{ github.event.issue.number }}
        issueBody="${{ github.event.issue.body }}"
        
        # Check for keywords and add labels
        labels=""
        
        if [[ "$issueBody" == *improvement* || "$issueBody" == *feature* || "$issueBody" == *enhancement* ]]; then
          labels="$labels,enhancement"
        fi
        
        if [[ "$issueBody" == *bug* || "$issueBody" == *'not working'* || "$issueBody" == *fix* ]]; then
          labels="$labels,bug"
        fi
        
        if [[ "$issueBody" == *refactor* || "$issueBody" == *change* ]]; then
          labels="$labels,refactor"
        fi
        
        if [[ "$issueBody" == *test* ]]; then
          labels="$labels,testing"
        fi
        
        if [[ "$issueBody" == *documentation* ]]; then
          labels="$labels,documentation"
        fi

        # Add labels
        if [[ ! -z "$labels" ]]; then
          gh issue label $issueNumber --add $labels
        fi

        # Add to project board
        # This is a bit more complicated and may require additional setup or another API call
        echo "Code to add issue to project board goes here."

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
