#Credits ChatGPT 4.0

name: Issue Automation

on:
  issues:
    types: [opened]

jobs:
  process_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Assign to project board and add labels
      uses: actions/github-script@v5
      with:
        script: |
          const issueBody = context.issue.body;
          const issueNumber = context.issue.number;
          const repo = context.repo;

          const headers = {
            Authorization: `token ${process.env.GITHUB_TOKEN}`,
            Accept: 'application/vnd.github.v3+json'
          };
          
          // Add to project board
          await fetch(`https://api.github.com/projects/columns/1/cards`, {
            method: 'POST',
            headers: headers,
            body: JSON.stringify({
              content_id: issueNumber,
              content_type: 'Issue'
            })
          });

          // Check for keywords and add labels
          const labels = [];
          if (['improvement', 'feature', 'enhancement'].some(keyword => issueBody.includes(keyword))) {
            labels.push('enhancement');
          }
          if (['bug', 'not working', 'fix'].some(keyword => issueBody.includes(keyword))) {
            labels.push('bug');
          }
          if (['refactor', 'change'].some(keyword => issueBody.includes(keyword))) {
            labels.push('refactor');
          }
          if (issueBody.includes('test')) {
            labels.push('testing');
          }
          if (issueBody.includes('documentation')) {
            labels.push('documentation');
          }

          if (labels.length) {
            await fetch(`https://api.github.com/repos/${repo.owner}/${repo.repo}/issues/${issueNumber}/labels`, {
              method: 'POST',
              headers: headers,
              body: JSON.stringify(labels)
            });
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
