name: Issue Automation

on:
  issues:
    types: [opened]

jobs:
  process_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Assign to project board and add labels
      uses: actions/github-script@v5
      with:
        script: |
          const issueBody = context.issue.body;
          const issueNumber = context.issue.number;
          const repo = context.repo;

          // Add to project board
          await github.projects.createCard({
            column_id: '1', // Adjust this as necessary
            content_id: issueNumber,
            content_type: 'Issue'
          });

          // Check for keywords and add labels
          const labels = [];
          if (['improvement', 'feature', 'enhancement'].some(keyword => issueBody.includes(keyword))) {
            labels.push('enhancement');
          }
          if (['bug', 'not working', 'fix'].some(keyword => issueBody.includes(keyword))) {
            labels.push('bug');
          }
          if (['refactor', 'change'].some(keyword => issueBody.includes(keyword))) {
            labels.push('refactor');
          }
          if (issueBody.includes('test')) {
            labels.push('testing');
          }
          if (issueBody.includes('documentation')) {
            labels.push('documentation');
          }

          if (labels.length) {
            await github.issues.addLabels({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issueNumber,
              labels: labels
            });
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
