name: Pandoc-rapport

on:
  push:
    branches:
      - main 

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: -s ./docs/report.md -o docs/report.pdf