# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup20chirpremotedb

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build -c Release src/Chirp.Web

      #- name: Test
      #  run: |
      #    dotnet test test/Chirp.CoreTests
      #    dotnet test test/Chirp.InfrastructureTests
      #    dotnet test test/Chirp.WebTests

      - name: dotnet publish
        run: dotnet publish -c Release src/Chirp.Web -o src/Chirp.Web.Publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: Chirp.Web
          path: src/Chirp.Web.Publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: Chirp.Web
          path: ./Chirp.Web

      - name: Inspect downloaded artifact structure
        run: ls


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bdsagroup20chirprazor'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3C715B6F309145D2A489CCA05C6FA214 }}
          package: Chirp.Web
